FROM n8nio/runners:2.15.1

USER root
# Instalujemy pandas bezpośrednio do wirtualnego środowiska n8n
RUN cd /opt/runners/task-runner-python && \
    uv pip install --python .venv/bin/python pandas

# Kopiujemy nasz plik konfiguracyjny do kontenera
COPY n8n-task-runners.json /etc/n8n-task-runners.json
RUN chown runner:runner /etc/n8n-task-runners.json

USER runner
